name: Publish Xdeps to PyPI

on:
  release:
    types: [released, edited]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build the package
      shell: bash -el {0}
      run: |
        /opt/python/cp310-cp310/bin/pip install build && \
        /opt/python/cp310-cp310/bin/python -m build --sdist && \
        /opt/python/cp310-cp310/bin/python -m build --wheel --outdir rawdist && \
        auditwheel repair rawdist/*.whl -w dist/
    - name: Store the dist as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Xdeps to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/xdeps
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
